"""Initial_migration_with_connections_and_presence

Revision ID: d035c5ba9b03
Revises: 
Create Date: 2026-01-10 12:32:35.441952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd035c5ba9b03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('connected_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connected_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_connections_id'), 'user_connections', ['id'], unique=False)
    op.create_table('user_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_presence_id'), 'user_presence', ['id'], unique=False)
    op.add_column('calls', sa.Column('caller_id', sa.Integer(), nullable=True))
    op.add_column('calls', sa.Column('callee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calls', 'users', ['callee_id'], ['id'])
    op.create_foreign_key(None, 'calls', 'users', ['caller_id'], ['id'])
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('connection_code', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('connection_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_connection_code'), 'users', ['connection_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_connection_code'), table_name='users')
    op.drop_column('users', 'connection_code_expires_at')
    op.drop_column('users', 'connection_code')
    op.drop_column('users', 'display_name')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_column('calls', 'callee_id')
    op.drop_column('calls', 'caller_id')
    op.drop_index(op.f('ix_user_presence_id'), table_name='user_presence')
    op.drop_table('user_presence')
    op.drop_index(op.f('ix_user_connections_id'), table_name='user_connections')
    op.drop_table('user_connections')
    # ### end Alembic commands ###
